rover_node:
  ros__parameters:
    team: "BLUE"
    policy_zip_path: "/home/swarm/code/ctf_ros2_ws/install/ctf_rover/share/ctf_rover/policies/iter1_bay_blue_br.zip"
    arrival_tolerance: 0.5  # metres
