rover_node:
  ros__parameters:
    team: "BLUE"
    team_index: 1
    policy_zip_path: "/home/namanagg/marl_ctf/blue_v4_hybrid_mappo_new_map/blue_mappo_final.zip"
    all_rover_names:
      - "RR01"
      - "RR02"
      - "RR03"
      - "RR04"
    all_rover_teams:
      - "BLUE"
      - "BLUE"
      - "RED"
      - "RED"
    all_rover_team_indices:
      - 0
      - 1
      - 0
      - 1
    arrival_tolerance: 0.5
