rover_node:
  ros__parameters:
    team: "RED"
    # Path after `colcon build`: $(ros2 pkg prefix ctf_rover)/share/ctf_rover/policies/GNN_PPO_RedBR_opp_fh1_flag_uniform.zip
    policy_zip_path: "/home/swarm/code/ctf_ros2_ws/install/ctf_rover/share/ctf_rover/policies/GNN_PPO_RedBR_opp_fh1_flag_uniform.zip"
    arrival_tolerance: 0.5  # metres
